In [5]:
import torch 
from torch import nn

softmax = nn.Softmax()

Y_a = torch.randn((5,5))
Y_b = torch.randn((5, 5))

In [6]:
# binarization
softmax(Y_a, dim)

/Users/jkirsch/.pyenv/versions/ecs_fp/lib/python3.12/site-packages/torch/nn/modules/module.py:1532: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  return self._call_impl(*args, **kwargs)


tensor([[0.7666, 0.0433, 0.0945, 0.0229, 0.0727],
        [0.0489, 0.5317, 0.1392, 0.1268, 0.1533],
        [0.3564, 0.2391, 0.1278, 0.1487, 0.1281],
        [0.0995, 0.1152, 0.0899, 0.2497, 0.4456],
        [0.2687, 0.0579, 0.1472, 0.1801, 0.3461]])

In [7]:
sigmoid = nn.Sigmoid()

sigmoid(Y_a)

tensor([[0.8571, 0.2532, 0.4251, 0.1519, 0.3627],
        [0.2801, 0.8088, 0.5255, 0.5022, 0.5495],
        [0.4610, 0.3647, 0.2347, 0.2630, 0.2352],
        [0.6058, 0.6403, 0.5814, 0.7941, 0.8731],
        [0.7053, 0.3404, 0.5674, 0.6160, 0.7550]])

In [9]:
# sigmoid squashes to [0, 1] but not normalized probabilities
# do a pass that normalizes across channels using softmax 
# update Dice loss accordingly
preds = torch.randn([3, 5, 25, 25])

In [10]:
preds = torch.randn([3, 5, 25, 25])
sigmoid = nn.Sigmoid()
softmax_channel = nn.Softmax(dim=1) # across channel dim 

preds = sigmoid(preds)
preds_proba = softmax_channel(preds)



In [12]:
preds_proba.sum(dim=1)

tensor([[[1.0000, 1.0000, 1.0000,  ..., 1.0000, 1.0000, 1.0000],
         [1.0000, 1.0000, 1.0000,  ..., 1.0000, 1.0000, 1.0000],
         [1.0000, 1.0000, 1.0000,  ..., 1.0000, 1.0000, 1.0000],
         ...,
         [1.0000, 1.0000, 1.0000,  ..., 1.0000, 1.0000, 1.0000],
         [1.0000, 1.0000, 1.0000,  ..., 1.0000, 1.0000, 1.0000],
         [1.0000, 1.0000, 1.0000,  ..., 1.0000, 1.0000, 1.0000]],

        [[1.0000, 1.0000, 1.0000,  ..., 1.0000, 1.0000, 1.0000],
         [1.0000, 1.0000, 1.0000,  ..., 1.0000, 1.0000, 1.0000],
         [1.0000, 1.0000, 1.0000,  ..., 1.0000, 1.0000, 1.0000],
         ...,
         [1.0000, 1.0000, 1.0000,  ..., 1.0000, 1.0000, 1.0000],
         [1.0000, 1.0000, 1.0000,  ..., 1.0000, 1.0000, 1.0000],
         [1.0000, 1.0000, 1.0000,  ..., 1.0000, 1.0000, 1.0000]],

        [[1.0000, 1.0000, 1.0000,  ..., 1.0000, 1.0000, 1.0000],
         [1.0000, 1.0000, 1.0000,  ..., 1.0000, 1.0000, 1.0000],
         [1.0000, 1.0000, 1.0000,  ..., 1.0000, 1.0000, 1.

In [14]:
preds_proba.shape

torch.Size([3, 5, 25, 25])

In [15]:
max_values, max_indices = torch.max(preds_proba, dim=1)

max_indices.shape

torch.Size([3, 25, 25])

In [17]:
max_indices[0, :, :]

tensor([[1, 4, 4, 0, 0, 4, 4, 1, 1, 2, 3, 1, 1, 2, 1, 1, 1, 1, 1, 2, 3, 2, 3, 3,
         1],
        [1, 1, 0, 4, 4, 0, 1, 3, 1, 2, 0, 2, 3, 3, 4, 4, 1, 0, 1, 2, 4, 3, 3, 4,
         3],
        [0, 1, 1, 3, 3, 3, 4, 4, 4, 2, 4, 0, 2, 3, 0, 2, 1, 4, 3, 1, 0, 1, 1, 4,
         0],
        [1, 4, 0, 2, 0, 2, 0, 4, 3, 4, 4, 4, 2, 0, 0, 1, 2, 2, 3, 0, 1, 4, 1, 2,
         1],
        [1, 3, 2, 4, 1, 3, 3, 3, 4, 2, 2, 3, 2, 0, 0, 1, 0, 1, 3, 2, 1, 2, 1, 0,
         2],
        [4, 0, 4, 1, 3, 2, 3, 4, 4, 4, 2, 3, 4, 2, 1, 0, 1, 2, 0, 3, 0, 0, 4, 0,
         0],
        [0, 2, 3, 1, 4, 0, 4, 3, 4, 3, 1, 4, 2, 0, 2, 3, 3, 2, 2, 2, 0, 1, 4, 0,
         2],
        [4, 2, 0, 0, 2, 2, 1, 3, 4, 1, 0, 1, 0, 0, 4, 4, 2, 3, 0, 1, 0, 2, 2, 3,
         2],
        [0, 3, 3, 1, 3, 3, 4, 4, 2, 3, 0, 1, 2, 0, 2, 2, 4, 0, 2, 1, 3, 0, 1, 0,
         0],
        [2, 4, 3, 2, 3, 0, 0, 0, 3, 1, 1, 2, 4, 4, 4, 4, 4, 1, 1, 4, 0, 4, 3, 3,
         4],
        [1, 4, 0, 0, 1, 4, 1, 2, 1, 3, 3, 4, 0, 1, 2, 3, 2, 